### ISSUE TITLE
nori2 question

### ISSUE THREAD

**Issue by edmandzhao** [lhaippp/DMHomo#2]
Hi, thank you for your fantastic paper.
I encountered an issue while loading the nori2 library file, which is on "import nori2 as nori". Where should I download the nori2 package from?

**Comment by lhaippp** [comment]
sry for the issue, it is a private package, let me update the codes

**Comment by lhaippp** [comment]
done

**Comment by edmandzhao** [comment]
> done

Thank you very much for your answer. Looking forward to your future work.
